
package me.jiangcai.loveport.service.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "DisabledServicePortType", targetNamespace = "http://disabled.service.widewisdom.cn")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface DisabledServicePortType {


    /**
     * @param in0
     * @return returns me.jiangcai.loveport.service.wsdl.ServiceResponse
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://disabled.service.widewisdom.cn")
    @RequestWrapper(localName = "welcome", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.Welcome")
    @ResponseWrapper(localName = "welcomeResponse", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.WelcomeResponse")
    public ServiceResponse welcome(
            @WebParam(name = "in0", targetNamespace = "http://disabled.service.widewisdom.cn")
                    NetworkCredential in0);

    /**
     * @param in0
     * @return returns me.jiangcai.loveport.service.wsdl.DisabledResponse
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://disabled.service.widewisdom.cn")
    @RequestWrapper(localName = "singleQuery", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.SingleQuery")
    @ResponseWrapper(localName = "singleQueryResponse", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.SingleQueryResponse")
    public DisabledResponse singleQuery(
            @WebParam(name = "in0", targetNamespace = "http://disabled.service.widewisdom.cn")
                    DisabledRequest in0);

    /**
     * @param in0
     * @return returns me.jiangcai.loveport.service.wsdl.QueryResponse
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://disabled.service.widewisdom.cn")
    @RequestWrapper(localName = "queryDisabled", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.QueryDisabled")
    @ResponseWrapper(localName = "queryDisabledResponse", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.QueryDisabledResponse")
    public QueryResponse queryDisabled(
            @WebParam(name = "in0", targetNamespace = "http://disabled.service.widewisdom.cn")
                    QueryRequest in0);

    /**
     * @param in0
     * @return returns me.jiangcai.loveport.service.wsdl.DisabledQueryResponse
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://disabled.service.widewisdom.cn")
    @RequestWrapper(localName = "getIndividualQuery", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.GetIndividualQuery")
    @ResponseWrapper(localName = "getIndividualQueryResponse", targetNamespace = "http://disabled.service.widewisdom.cn", className = "me.jiangcai.loveport.service.wsdl.GetIndividualQueryResponse")
    public DisabledQueryResponse getIndividualQuery(
            @WebParam(name = "in0", targetNamespace = "http://disabled.service.widewisdom.cn")
                    DisabledQueryRequest in0);

}
