
package me.jiangcai.loveport.service.wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "DisabledService", targetNamespace = "http://disabled.service.widewisdom.cn", wsdlLocation = "http://webservice.zjdpf.org.cn/disabledservices/list/DisabledService?wsdl")
public class DisabledService
        extends Service {

    private final static URL DISABLEDSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISABLEDSERVICE_EXCEPTION;
    private final static QName DISABLEDSERVICE_QNAME = new QName("http://disabled.service.widewisdom.cn", "DisabledService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webservice.zjdpf.org.cn/disabledservices/list/DisabledService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
            throw e;
        }
        DISABLEDSERVICE_WSDL_LOCATION = url;
        DISABLEDSERVICE_EXCEPTION = e;
    }

    public DisabledService() {
        super(__getWsdlLocation(), DISABLEDSERVICE_QNAME);
    }

    public DisabledService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISABLEDSERVICE_QNAME, features);
    }

    public DisabledService(URL wsdlLocation) {
        super(wsdlLocation, DISABLEDSERVICE_QNAME);
    }

    public DisabledService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISABLEDSERVICE_QNAME, features);
    }

    public DisabledService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DisabledService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DISABLEDSERVICE_EXCEPTION != null) {
            throw DISABLEDSERVICE_EXCEPTION;
        }
        return DISABLEDSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns DisabledServicePortType
     */
    @WebEndpoint(name = "DisabledServiceHttpPort")
    public DisabledServicePortType getDisabledServiceHttpPort() {
        return super.getPort(new QName("http://disabled.service.widewisdom.cn", "DisabledServiceHttpPort"), DisabledServicePortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DisabledServicePortType
     */
    @WebEndpoint(name = "DisabledServiceHttpPort")
    public DisabledServicePortType getDisabledServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://disabled.service.widewisdom.cn", "DisabledServiceHttpPort"), DisabledServicePortType.class, features);
    }

}
